title: Wan Nur Shafiqah
logo: ![Image](https://github.com/user-attachments/assets/98a9e321-39f6-4e73-b19b-a245580279ac)
description: I make data work harder so people don't have to.  Automation is my playground.
theme: jekyll-theme-dinky
